#의사결정나무 - 다중분류(multiclass classification)
- heart disease dataset


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
 ! wget https://raw.githubusercontent.com/devdio/datasets/main/heart_disease.csv

--2023-11-30 12:08:49--  https://raw.githubusercontent.com/devdio/datasets/main/heart_disease.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11328 (11K) [text/plain]
Saving to: ‘heart_disease.csv’

heart_disease.csv   100%[===================>]  11.06K  --.-KB/s    in 0.001s  

2023-11-30 12:08:49 (14.2 MB/s) - ‘heart_disease.csv’ saved [11328/11328]



In [3]:
heart=pd.read_csv('heart_disease.csv')

In [4]:
heart.shape

(303, 14)

In [5]:
df=heart

In [6]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

##2. 데이터 탐색

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [8]:
df.describe().T

count        mean        std    min    25%    50%    75%    max
age       303.0   54.366337   9.082101   29.0   47.5   55.0   61.0   77.0
sex       303.0    0.683168   0.466011    0.0    0.0    1.0    1.0    1.0
cp        303.0    0.966997   1.032052    0.0    0.0    1.0    2.0    3.0
trestbps  303.0  131.623762  17.538143   94.0  120.0  130.0  140.0  200.0
chol      303.0  246.264026  51.830751  126.0  211.0  240.0  274.5  564.0
fbs       303.0    0.148515   0.356198    0.0    0.0    0.0    0.0    1.0
restecg   303.0    0.528053   0.525860    0.0    0.0    1.0    1.0    2.0
thalach   303.0  149.646865  22.905161   71.0  133.5  153.0  166.0  202.0
exang     303.0    0.326733   0.469794    0.0    0.0    0.0    1.0    1.0
oldpeak   303.0    1.039604   1.161075    0.0    0.0    0.8    1.6    6.2
slope     303.0    1.399340   0.616226    0.0    1.0    1.0    2.0    2.0
ca        303.0    0.729373   1.022606    0.0    0.0    0.0    1.0    4.0
thal      303.0    2.313531   0.612277    0.0    2.0    2.0    3.0    3.0
target    303.0    0.544554   0.498835    0.0    0.0    1.0    1.0    1.0

In [9]:
X= df.drop("target",axis=1)
Y= df['target']

In [10]:
df['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

In [11]:
#테스트 데이터 분리
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y, test_size=0.2, stratify=Y,random_state=0)

In [12]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [13]:
from sklearn.preprocessing import StandardScaler

ss=StandardScaler()
X_train_s=ss.fit_transform(X_train)
X_train_s

array([[ 0.1762246 ,  0.63794729, -0.95894245, ..., -2.22991675,
        -0.71743331,  1.09984435],
       [ 0.39834103,  0.63794729, -0.95894245, ..., -0.61905151,
         2.17621437,  1.09984435],
       [-0.49012468, -1.56752763,  0.96690048, ..., -0.61905151,
        -0.71743331, -0.5035432 ],
       ...,
       [ 1.17574852, -1.56752763, -0.95894245, ..., -0.61905151,
         2.17621437,  1.09984435],
       [-0.15695004,  0.63794729, -0.95894245, ..., -0.61905151,
         1.21166515,  1.09984435],
       [ 0.95363209, -1.56752763,  0.96690048, ...,  0.99181372,
        -0.71743331, -0.5035432 ]])

In [14]:
type(X_train_s)

numpy.ndarray

In [15]:
type(Y_train)

pandas.core.series.Series

In [16]:
Y_train_s=np.array(Y_train)
Y_train_s
type(Y_train_s)

numpy.ndarray

In [17]:
Y_train_s

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1])

In [18]:
from sklearn.tree import DecisionTreeClassifier

clf=DecisionTreeClassifier()
clf.fit(X_train_s,Y_train_s)

DecisionTreeClassifier()

In [19]:
X_test_s=ss.fit_transform(X_test)
X_test_s

array([[-1.52316118,  0.86189161,  2.17130386,  0.48772384, -1.04118283,
        -0.26490647,  1.0856203 ,  1.25834558,  1.28536917,  0.20298185,
         0.91879598, -0.70501289,  1.2310418 ],
       [-0.98609278, -1.1602387 ,  0.14917355, -0.07681419, -0.39025301,
        -0.26490647, -0.92113237,  1.11928928, -0.77798661, -0.43608358,
        -0.77958446, -0.70501289, -0.55689986],
       [ 1.0547671 ,  0.86189161,  2.17130386, -1.20589026, -0.81800689,
        -0.26490647, -0.92113237, -0.31762588,  1.28536917,  0.52251456,
        -0.77958446, -0.70501289, -0.55689986],
       [ 1.0547671 , -1.1602387 ,  1.1602387 ,  0.48772384,  1.07898859,
        -0.26490647,  1.0856203 , -0.827499  , -0.77798661, -0.75561629,
         0.91879598, -0.70501289,  1.2310418 ],
       [-1.4157475 ,  0.86189161,  1.1602387 , -1.09298265, -0.09268509,
        -0.26490647,  1.0856203 ,  1.30469769, -0.77798661, -0.91538265,
         0.91879598, -0.70501289, -0.55689986],
       [-1.09350646,  0.861891

In [20]:
Y_pred =clf.predict(X_test_s)
Y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1])

In [21]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
def print_metrics(Y_test,Y_pred):
  acc= accuracy_score(Y_test,Y_pred)
  re= recall_score(Y_test,Y_pred)
  pr= precision_score(Y_test,Y_pred)             #  정확도는 이진분류랑 다중분류 계산하는게 같은데 나머진 다 다르다
  f1= f1_score(Y_test,Y_pred)                    # 보통 average가 defalt 값이 이진분류라 바꿔줘야함
  print('정확도:',acc)
  print('재현율:',re)
  print('정밀도:',pr)
  print('f1스코어:',f1)
print_metrics(Y_test,Y_pred)

정확도: 0.8032786885245902
재현율: 0.8484848484848485
정밀도: 0.8
f1스코어: 0.823529411764706
