#랜덤포레스트 - 다중분류
-human Activities dataset

##1.데이터 준비

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
train = pd.read_csv('train.csv',encoding='cp949')
test = pd.read_csv('test.csv',encoding='cp949')

In [15]:
train.shape

(7352, 563)

In [16]:
df=train

In [17]:
df.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.923527         -0.934724  ...                        -0.710304   
1         -0.957686         -0.943068  ...                        -0.861499   
2         -0.977469         -0.938692  ...                        -0.760104   
3         -0.989302         -0.938692  ...                        -0.482845   
4         -0.990441         -0.942469  ...                        -0.699205   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.112754                              0.030400   
1                     0.053477                             -0.007435   
2                    -0.118559                              0.177899   
3                    -0.036788                             -0.012892   
4                     0.123320                              0.122542   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.464761                             -0.018446   
1                         -0.732626                              0.703511   
2                          0.100699                              0.808529   
3                          0.640011                             -0.485366   
4                          0.693578                             -0.615971   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  subject  \
0             -0.841247              0.179941             -0.058627        1   
1             -0.844788              0.180289             -0.054317        1   
2             -0.848933              0.180637             -0.049118        1   
3             -0.848649              0.181935             -0.047663        1   
4             -0.847865              0.185151             -0.043892        1   

   Activity  
0  STANDING  
1  STANDING  
2  STANDING  
3  STANDING  
4  STANDING  

[5 rows x 563 columns]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7352 entries, 0 to 7351
Columns: 563 entries, tBodyAcc-mean()-X to Activity
dtypes: float64(561), int64(1), object(1)
memory usage: 31.6+ MB


In [19]:
df.describe().T

count       mean       std       min  \
tBodyAcc-mean()-X                     7352.0   0.274488  0.070261 -1.000000   
tBodyAcc-mean()-Y                     7352.0  -0.017695  0.040811 -1.000000   
tBodyAcc-mean()-Z                     7352.0  -0.109141  0.056635 -1.000000   
tBodyAcc-std()-X                      7352.0  -0.605438  0.448734 -1.000000   
tBodyAcc-std()-Y                      7352.0  -0.510938  0.502645 -0.999873   
...                                      ...        ...       ...       ...   
angle(tBodyGyroJerkMean,gravityMean)  7352.0  -0.005981  0.477975 -1.000000   
angle(X,gravityMean)                  7352.0  -0.489547  0.511807 -1.000000   
angle(Y,gravityMean)                  7352.0   0.058593  0.297480 -1.000000   
angle(Z,gravityMean)                  7352.0  -0.056515  0.279122 -1.000000   
subject                               7352.0  17.413085  8.975143  1.000000   

                                           25%        50%        75%  \
tBodyAcc-mean()-X                     0.262975   0.277193   0.288461   
tBodyAcc-mean()-Y                    -0.024863  -0.017219  -0.010783   
tBodyAcc-mean()-Z                    -0.120993  -0.108676  -0.097794   
tBodyAcc-std()-X                     -0.992754  -0.946196  -0.242813   
tBodyAcc-std()-Y                     -0.978129  -0.851897  -0.034231   
...                                        ...        ...        ...   
angle(tBodyGyroJerkMean,gravityMean) -0.376341  -0.000368   0.359368   
angle(X,gravityMean)                 -0.812065  -0.709417  -0.509079   
angle(Y,gravityMean)                 -0.017885   0.182071   0.248353   
angle(Z,gravityMean)                 -0.143414   0.003181   0.107659   
subject                               8.000000  19.000000  26.000000   

                                            max  
tBodyAcc-mean()-X                      1.000000  
tBodyAcc-mean()-Y                      1.000000  
tBodyAcc-mean()-Z                      1.000000  
tBodyAcc-std()-X                       1.000000  
tBodyAcc-std()-Y                       0.916238  
...                                         ...  
angle(tBodyGyroJerkMean,gravityMean)   0.996078  
angle(X,gravityMean)                   1.000000  
angle(Y,gravityMean)                   0.478157  
angle(Z,gravityMean)                   1.000000  
subject                               30.000000  

[562 rows x 8 columns]

In [20]:
df.isna().sum().sum()         # sum 한번 더 쓰면 전체의 전체

0

In [23]:
df['Activity'].value_counts()

LAYING                1407
STANDING              1374
SITTING               1286
WALKING               1226
WALKING_UPSTAIRS      1073
WALKING_DOWNSTAIRS     986
Name: Activity, dtype: int64

In [22]:
X_train = df.drop('Activity',axis=1)
Y_train = df['Activity']

In [24]:
from sklearn.preprocessing import StandardScaler

ss=StandardScaler()
X_train_s=ss.fit_transform(X_train)
X_train_s[:5]

array([[ 0.20064157, -0.0636826 , -0.41962845, ...,  0.40794614,
        -0.00756789, -1.8288513 ],
       [ 0.05594788,  0.03148567, -0.25390836, ...,  0.40911698,
         0.00787517, -1.8288513 ],
       [ 0.07351535, -0.04341648, -0.07629468, ...,  0.4102883 ,
         0.02650234, -1.8288513 ],
       [ 0.06669577, -0.20842166, -0.24971245, ...,  0.41465007,
         0.03171414, -1.8288513 ],
       [ 0.03046897,  0.02758722, -0.10984784, ...,  0.42546296,
         0.04522502, -1.8288513 ]])

In [25]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Y_train=le.fit_transform(Y_train)
Y_train

array([2, 2, 2, ..., 5, 5, 5])

In [26]:
type(X_train_s),type(Y_train)

(numpy.ndarray, numpy.ndarray)

In [27]:
from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier()
clf.fit(X_train_s,Y_train)

RandomForestClassifier()

In [28]:
dff = test

In [29]:
X_test = dff.drop('Activity',axis=1)
Y_test = dff['Activity']

In [30]:
X_test_s=ss.fit_transform(X_test)

In [31]:
Y_test=le.fit_transform(Y_test)

In [32]:
type(X_test_s), type(Y_test)

(numpy.ndarray, numpy.ndarray)

In [33]:
Y_pred =clf.predict(X_test_s)
Y_pred

array([2, 2, 2, ..., 5, 5, 5])

In [34]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
def print_metrics(Y_test,Y_pred):
  acc= accuracy_score(Y_test,Y_pred)
  re= recall_score(Y_test,Y_pred,average='macro')
  pr= precision_score(Y_test,Y_pred,average='macro')
  f1= f1_score(Y_test,Y_pred,average='macro')
  print('정확도:',acc)
  print('재현율:',re)
  print('정밀도:',pr)
  print('f1스코어:',f1)
print_metrics(Y_test,Y_pred)

정확도: 0.9117746861214795
재현율: 0.9127386903086961
정밀도: 0.9176231401550781
f1스코어: 0.9109732287651021


In [35]:
#튜닝

In [36]:
from sklearn.model_selection import GridSearchCV

grid_params = {
    "max_depth":[13,16],
    'n_estimators':[80,100]
}

In [37]:
gs = GridSearchCV(clf, grid_params, cv=5,verbose=5)
gs.fit(X_train_s, Y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV 1/5] END .....max_depth=13, n_estimators=80;, score=0.910 total time=   9.8s
[CV 2/5] END .....max_depth=13, n_estimators=80;, score=0.901 total time=   9.1s
[CV 3/5] END .....max_depth=13, n_estimators=80;, score=0.907 total time=   8.7s
[CV 4/5] END .....max_depth=13, n_estimators=80;, score=0.929 total time=  10.0s
[CV 5/5] END .....max_depth=13, n_estimators=80;, score=0.951 total time=   8.5s
[CV 1/5] END ....max_depth=13, n_estimators=100;, score=0.917 total time=  11.7s
[CV 2/5] END ....max_depth=13, n_estimators=100;, score=0.897 total time=  12.0s
[CV 3/5] END ....max_depth=13, n_estimators=100;, score=0.901 total time=  10.9s
[CV 4/5] END ....max_depth=13, n_estimators=100;, score=0.929 total time=  11.6s
[CV 5/5] END ....max_depth=13, n_estimators=100;, score=0.949 total time=  12.3s
[CV 1/5] END .....max_depth=16, n_estimators=80;, score=0.910 total time=   9.6s
[CV 2/5] END .....max_depth=16, n_estimators=80;,

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [13, 16], 'n_estimators': [80, 100]},
             verbose=5)

In [38]:
gs.best_params_

{'max_depth': 16, 'n_estimators': 100}

In [39]:
gs.best_score_

0.9217946974847043

In [40]:
#최종학습

In [41]:
clf = RandomForestClassifier(max_depth= 16, n_estimators= 80)
clf.fit(X_train_s,Y_train)

RandomForestClassifier(max_depth=16, n_estimators=80)